#- coding: utf-8 -#
from os import environ

ARDUINO_USB_PORT = environ.get('ARDUINO_USB_PORT', '/dev/ttyUSB0')
ARDUINO_BAUD_RATE = int(environ.get('ARDUINO_BAUD_RATE', 9600))
ARDUINO_NUMBER_OF_INPUTS = int(environ.get('ARDUINO_NUMBER_OF_INPUTS', 2))
GRAPHS_OUTPUT_DIRECTORY = environ.get('GRAPHS_OUTPUT_DIRECTORY', './')
MEMCACHED_HOST = environ.get('MEMCACHED_HOST','127.0.0.1:11211')
MEMCACHE_EXPIRATION_TIME =  int(environ.get('MEMCACHE_EXPIRATION_TIME', 24 * 60  * 60))
SAMPLE_PERIOD = int(environ.get('SAMPLE_PERIOD', 60))
SAMPLE_WINDOW = int(environ.get('SAMPLE_WINDOW', 2880))
